"""Curated registry of Missouri public-data sources for the chatbot roadmap."""

from __future__ import annotations

from typing import Any


PUBLIC_SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "map",
        "label": "Missouri Accountability Portal",
        "domain": "public finance",
        "url": "https://mapyourtaxes.mo.gov/MAP/Portal/Default.aspx",
        "status": "indexed",
        "access": "Public downloads and daily-updated MAP web tables.",
        "use_case": "Expenditures, employee pay, tax credits, federal grants, budget restrictions, bonds, and related transparency questions.",
        "risk": "Row-level public records need careful UI limits and privacy boundaries.",
    },
    {
        "key": "data_mo_catalog",
        "label": "State of Missouri data.mo.gov catalog",
        "domain": "open data catalog",
        "url": "https://data.mo.gov/data.json",
        "status": "cataloged",
        "access": "Socrata/data.json metadata and dataset CSV/JSON exports when public.",
        "use_case": "Discover and prioritize state datasets, including health, labor, natural resources, regulatory, and government administration data.",
        "risk": "Dataset schemas vary; some views are maps, files, filters, or stale records.",
    },
    {
        "key": "contracts",
        "label": "MissouriBUYS and OA contract search",
        "domain": "procurement",
        "url": "https://missouribuys.mo.gov/contractboard",
        "status": "indexed",
        "access": "Public contract board plus legacy OA statewide contract detail pages and document links.",
        "use_case": "Contract number, vendor, category, dates, document links, and MAP vendor-payment context.",
        "risk": "Legacy HTML/CGI structure can change; new MissouriBUYS transition may shift data surfaces.",
    },
    {
        "key": "contract_documents",
        "label": "OA contract award documents",
        "domain": "procurement documents",
        "url": "https://archive.oa.mo.gov/purch/contracts/",
        "status": "local optional extraction",
        "access": "Public PDF contract documents; downloaded and parsed locally only when a capped document index is built.",
        "use_case": "Plain-English contract explanations: what the state is buying, who the vendor is, term, renewal, contract type, and where to read the source document.",
        "risk": "PDF extraction can be imperfect; downloads must be capped to avoid storage spikes.",
    },
    {
        "key": "dese",
        "label": "DESE School Data",
        "domain": "education",
        "url": "https://dese.mo.gov/school-data",
        "status": "source indexed",
        "access": "Official school-data pages, dashboards, school directory exports, and public MCDS/DESE app surfaces.",
        "use_case": "District/school accountability, assessment, staff, finance, directory, and student-characteristic summaries.",
        "risk": "Some DESE surfaces are apps or secure portals; ingest only public downloadable outputs.",
    },
    {
        "key": "dhss",
        "label": "DHSS Data, Surveillance Systems & Statistical Reports",
        "domain": "public health",
        "url": "https://health.mo.gov/data/",
        "status": "source indexed",
        "access": "Public dashboards, profiles, reports, and aggregate health datasets.",
        "use_case": "County profiles, births, deaths, hospitalizations/PAS, BRFSS, opioid dashboards, and aggregate public-health trend explanations.",
        "risk": "Health data requires suppression, aggregation, and no person-level records.",
    },
    {
        "key": "mshp_sac",
        "label": "MSHP Statistical Analysis Center data files",
        "domain": "public safety",
        "url": "https://www.mshp.dps.mo.gov/MSHPWeb/SAC/data_960grid.html",
        "status": "indexed",
        "access": "Small public Excel files for crime, crash, traffic arrest, and related aggregate tables.",
        "use_case": "Crash severity, fatalities, injuries, rates, alcohol/speed/young-driver/older-driver/commercial/motorcycle factors.",
        "risk": "Excel parsing dependency; avoid person-level incident reports.",
    },
    {
        "key": "meric",
        "label": "MERIC labor and unemployment data",
        "domain": "labor market",
        "url": "https://meric.mo.gov/data/unemployment",
        "status": "indexed",
        "access": "Public reports, dashboard links, local unemployment data, and the LAUS CSV route.",
        "use_case": "Exact current Missouri/county unemployment rate, labor force, employment, and unemployed-count lookup; source discovery for wage, industry, projection, and regional profile questions.",
        "risk": "Many releases are PDFs or dashboards; exact current values need update timestamps.",
    },
    {
        "key": "dnr",
        "label": "Missouri DNR data and e-services",
        "domain": "environment",
        "url": "https://dnr.mo.gov/data-e-services",
        "status": "source indexed",
        "access": "Public environmental datasets, ArcGIS services, water permits, drinking water reports, impaired waters, and water-quality tools.",
        "use_case": "Water permits, public water systems, impaired waters, water quality, air/environmental reports, and GIS-style lookups.",
        "risk": "Many surfaces are search tools or map services; normalize by dataset before answering exact questions.",
    },
    {
        "key": "msdis",
        "label": "MSDIS geospatial open data",
        "domain": "geospatial",
        "url": "https://www.msdis.missouri.edu/",
        "status": "source indexed",
        "access": "Missouri GIS downloads, ArcGIS services, imagery, elevation, LiDAR, and vector layers.",
        "use_case": "County boundaries, administrative geography, public facilities, environmental overlays, and map-backed context.",
        "risk": "Imagery/LiDAR can be very large; start with vector metadata and small layers.",
    },
    {
        "key": "modot",
        "label": "MoDOT traffic and transportation data",
        "domain": "transportation",
        "url": "https://www.modot.org/modatazone/traffic",
        "status": "source indexed",
        "access": "Public MoDOT traffic data tools, reports, and transportation data pages.",
        "use_case": "Traffic counts, road/route context, safety/volume references, and transportation-data source discovery.",
        "risk": "Some values live behind apps or map tools; start with source links and downloadable reports.",
    },
    {
        "key": "state_auditor",
        "label": "Missouri State Auditor reports",
        "domain": "audits and accountability",
        "url": "https://auditor.mo.gov/AuditReport/Menu",
        "status": "source indexed",
        "access": "Official audit-report search pages and local government report links.",
        "use_case": "Plain-English explanations of audit findings, local government financial reports, tax-increment financing reports, forfeiture reports, and data-breach notices.",
        "risk": "Reports are often PDFs or JavaScript-backed search results; cite report dates and avoid implying an audit finding applies beyond the audited entity.",
    },
    {
        "key": "dor_reports",
        "label": "Missouri Department of Revenue public reports",
        "domain": "tax and revenue",
        "url": "https://dor.mo.gov/public-reports/",
        "status": "indexed",
        "access": "Official downloadable public reports for taxable sales, food tax, tax credits, vehicle/dealer reports, and Working Family Tax Credit summaries.",
        "use_case": "Exact aggregate lookup for indexed county taxable sales, business locations, vehicle counts, driver totals, dealer counts, and SIC location counts; source discovery for other revenue reports.",
        "risk": "Some reports suppress small counts; preserve suppression symbols and explain update periods.",
    },
    {
        "key": "mec",
        "label": "Missouri Ethics Commission public records",
        "domain": "ethics and campaign finance",
        "url": "https://mec.mo.gov/",
        "status": "source indexed",
        "access": "Public campaign-finance, lobbying, committee, commission-action, annual-report, and ethics-law search surfaces.",
        "use_case": "Campaign finance, committee contributions/expenditures, lobbyist reports, commission actions, and public ethics-law context.",
        "risk": "Political-finance data needs careful entity matching and should distinguish filings from conclusions or allegations.",
    },
    {
        "key": "sos_elections",
        "label": "Missouri Secretary of State election results",
        "domain": "elections",
        "url": "https://www.sos.mo.gov/elections/s_default",
        "status": "source indexed",
        "access": "Official election-results, candidate, ballot-measure, voter-turnout, and election-calendar pages.",
        "use_case": "Official statewide/county election result source discovery, candidate/ballot context, and voter-turnout references where public files are available.",
        "risk": "Not all result formats are bulk-download friendly; avoid voter-level data.",
    },
    {
        "key": "oa_budget",
        "label": "Office of Administration Budget and Planning",
        "domain": "budget and planning",
        "url": "https://oa.mo.gov/budget-and-planning",
        "status": "source indexed",
        "access": "Official budget, revenue, performance-measure, demographics, redistricting, and fiscal-policy pages.",
        "use_case": "Connect MAP spending to executive budget context, revenue estimates, performance measures, and state demographic planning.",
        "risk": "Budget documents can be proposal-stage or enacted-stage; label the stage and fiscal year.",
    },
    {
        "key": "child_care",
        "label": "DESE child care compliance dashboards",
        "domain": "child care",
        "url": "https://dese.mo.gov/childhood/child-care/child-care-data-dashboards",
        "status": "source indexed",
        "access": "Public dashboard pages for regulated child care facilities, slots, inspections, complaints, pending facilities, and licensing time.",
        "use_case": "Child-care capacity and compliance source discovery by quarter or topic.",
        "risk": "Facility-level complaint context should be cited directly and summarized carefully.",
    },
    {
        "key": "long_term_care",
        "label": "DHSS long-term care inspection data",
        "domain": "long-term care",
        "url": "https://health.mo.gov/safety/nursinghomesinspected/index.php",
        "status": "source indexed",
        "access": "Public long-term-care inspection pages and Show Me Long-Term Care search surfaces.",
        "use_case": "Nursing home, assisted living, residential care, facility-type, bed-count, inspection, and complaint source discovery.",
        "risk": "Health-care facility data should remain aggregate or source-cited; avoid medical advice or unsupported quality rankings.",
    },
    {
        "key": "psc",
        "label": "Missouri Public Service Commission reports",
        "domain": "utilities",
        "url": "https://psc.mo.gov/General/PSC_Reports",
        "status": "source indexed",
        "access": "Public PSC report volumes, utility information, annual report references, and rate-case context pages.",
        "use_case": "Explain utility regulation sources, rate-case documents, public reports, and utility consumer context.",
        "risk": "Utility cases are legal/regulatory records; distinguish filings, staff positions, orders, and final decisions.",
    },
    {
        "key": "cannabis",
        "label": "DHSS Division of Cannabis Regulation reports",
        "domain": "cannabis regulation",
        "url": "https://health.mo.gov/safety/cannabis/",
        "status": "source indexed",
        "access": "Official cannabis-regulation pages, annual reports, licensed facility references, dashboards, and regulatory updates.",
        "use_case": "Cannabis sales, license, facility, transfer-history, inspection, item-approval, and program-report source discovery.",
        "risk": "Some dashboards are current-period snapshots; cite update cadence and avoid legal advice.",
    },
    {
        "key": "agriculture",
        "label": "Missouri Agricultural Market News reports",
        "domain": "agriculture",
        "url": "https://agmarketnews.mo.gov/reports/",
        "status": "source indexed",
        "access": "Public agricultural market-report links for livestock, cattle, swine, sheep/goat, and regional auctions.",
        "use_case": "Agricultural price/report source discovery and plain-English market-report explanations.",
        "risk": "Market reports may link to federal AMS reports; cite report date and market region.",
    },
]


def catalog_by_status() -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in PUBLIC_SOURCE_CATALOG:
        grouped.setdefault(source["status"], []).append(source)
    return grouped
