"""Curated registry of Missouri public-data sources for the chatbot roadmap."""

from __future__ import annotations

from typing import Any


PUBLIC_SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "map",
        "label": "Missouri Accountability Portal",
        "domain": "public finance",
        "url": "https://mapyourtaxes.mo.gov/Map/Portal/Default.aspx",
        "status": "indexed",
        "access": "Public downloads and daily-updated MAP web tables.",
        "use_case": "Expenditures, employee pay, tax credits, federal grants, budget restrictions, bonds, and related transparency questions.",
        "risk": "Row-level public records need careful UI limits and privacy boundaries.",
    },
    {
        "key": "data_mo_catalog",
        "label": "State of Missouri data.mo.gov catalog",
        "domain": "open data catalog",
        "url": "https://data.mo.gov/data.json",
        "status": "indexed",
        "access": "Socrata/data.json metadata and dataset CSV/JSON exports when public.",
        "use_case": "Exact catalog metadata lookup for dataset counts, themes, dataset search, landing pages, and distribution links; prioritizes future parsers.",
        "risk": "Dataset schemas vary; some views are maps, files, filters, or stale records.",
    },
    {
        "key": "data_mo_education",
        "label": "data.mo.gov education datasets",
        "domain": "education",
        "url": "https://data.mo.gov/browse?category=Education",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV exports for selected education datasets.",
        "use_case": "Exact school/year lookup for high-school senior counts and completed FAFSA application counts, plus top-school rankings.",
        "risk": "This is a selected open-data education layer, not full DESE accountability, assessment, staff, or finance coverage.",
    },
    {
        "key": "data_mo_health",
        "label": "data.mo.gov public-health aggregates",
        "domain": "public health",
        "url": "https://data.mo.gov/d/fk75-fa28",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Missouri Communicable Disease Report.",
        "use_case": "Exact aggregate communicable-disease report lookup for current-week YTD counts, rates per 100k, 5-year median comparisons, and rankings.",
        "risk": "Aggregate surveillance reporting only; not medical advice and not full DHSS MICA/profile/BRFSS coverage.",
    },
    {
        "key": "data_mo_wic",
        "label": "DHSS WIC aggregates",
        "domain": "public health",
        "url": "https://data.mo.gov/d/diyi-fr2a",
        "status": "indexed",
        "access": "Public Socrata aggregate queries over DHSS WIC Data.",
        "use_case": "Exact county and municipality WIC household-row counts, redeemed net-benefit totals, average benefits, and top-county rankings.",
        "risk": "The source table is household-level public data; this project stores and returns aggregate county/municipality summaries only.",
    },
    {
        "key": "data_mo_ltc",
        "label": "data.mo.gov LTC directory and census",
        "domain": "long-term care",
        "url": "https://data.mo.gov/d/fenu-sipv",
        "status": "indexed",
        "access": "Public Socrata JSON exports for selected sanitized LTC Directory fields and aggregate LTC Census Report rows.",
        "use_case": "Exact county/city/facility long-term-care directory capacity lookup, level-of-care summaries, top-county capacity ranking, and statewide LTC census occupancy.",
        "risk": "Selected directory and census fields only; administrator names, phone numbers, mailing addresses, street addresses, inspections, complaints, and quality conclusions are not stored or returned.",
    },
    {
        "key": "data_mo_water",
        "label": "data.mo.gov DNR water datasets",
        "domain": "environment",
        "url": "https://data.mo.gov/d/3mwf-kse4",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Consumer Confidence Report public drinking-water system listing.",
        "use_case": "Exact county water-system counts, PWSID lookups, system-name lookups, and county rankings.",
        "risk": "Selected drinking-water system listing only; not full DNR water quality, permits, impaired waters, or GIS coverage.",
    },
    {
        "key": "data_mo_utility",
        "label": "data.mo.gov utility providers",
        "domain": "utilities",
        "url": "https://data.mo.gov/d/yeiz-h2m2",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Find A Missouri Utility city/county table.",
        "use_case": "Exact city/county electric, gas, water, and telephone provider lookup plus provider rankings.",
        "risk": "Selected utility-provider listing only; not full PSC filings, rate cases, annual reports, or legal/regulatory orders.",
    },
    {
        "key": "data_mo_agriculture",
        "label": "data.mo.gov agriculture feed samples",
        "domain": "agriculture",
        "url": "https://data.mo.gov/d/y9w9-qkg2",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for Missouri Department of Agriculture feed sample testing results.",
        "use_case": "Exact feed sample ID lookup, feed class counts and rankings, and selected nutrient guarantee/result questions.",
        "risk": "Selected feed sample testing table only; not full agricultural market reports, inspections, complaints, or enforcement coverage.",
    },
    {
        "key": "contracts",
        "label": "MissouriBUYS and OA contract search",
        "domain": "procurement",
        "url": "https://missouribuys.mo.gov/contractboard",
        "status": "indexed",
        "access": "Public contract board plus legacy OA statewide contract detail pages and document links.",
        "use_case": "Contract number, vendor, category, dates, document links, and MAP vendor-payment context.",
        "risk": "Legacy HTML/CGI structure can change; new MissouriBUYS transition may shift data surfaces.",
    },
    {
        "key": "contract_documents",
        "label": "OA contract award documents",
        "domain": "procurement documents",
        "url": "https://archive.oa.mo.gov/purch/contracts/",
        "status": "local optional extraction",
        "access": "Public PDF contract documents; downloaded and parsed locally only when a capped document index is built.",
        "use_case": "Plain-English contract explanations: what the state is buying, who the vendor is, term, renewal, contract type, and where to read the source document.",
        "risk": "PDF extraction can be imperfect; downloads must be capped to avoid storage spikes.",
    },
    {
        "key": "dese",
        "label": "DESE School Data",
        "domain": "education",
        "url": "https://dese.mo.gov/school-data",
        "status": "source indexed",
        "access": "Official school-data pages, dashboards, school directory exports, and public MCDS/DESE app surfaces.",
        "use_case": "District/school accountability, assessment, staff, finance, directory, and student-characteristic summaries; selected School Directory exact lookup is implemented.",
        "risk": "Some DESE surfaces are apps or secure portals; ingest only public downloadable outputs and suppress contact/person fields from directory PDFs.",
    },
    {
        "key": "dhss",
        "label": "DHSS Data, Surveillance Systems & Statistical Reports",
        "domain": "public health",
        "url": "https://health.mo.gov/data/",
        "status": "source indexed",
        "access": "Public dashboards, profiles, reports, and aggregate health datasets.",
        "use_case": "County profiles, births, deaths, hospitalizations/PAS, BRFSS, opioid dashboards, and aggregate public-health trend explanations.",
        "risk": "Health data requires suppression, aggregation, and no person-level records.",
    },
    {
        "key": "mshp_sac",
        "label": "MSHP Statistical Analysis Center data files",
        "domain": "public safety",
        "url": "https://www.mshp.dps.mo.gov/MSHPWeb/SAC/data_960grid.html",
        "status": "indexed",
        "access": "Small public Excel files for crime, crash, traffic arrest, and related aggregate tables.",
        "use_case": "Crash severity, fatalities, injuries, rates, alcohol/speed/young-driver/older-driver/commercial/motorcycle factors.",
        "risk": "Excel parsing dependency; avoid person-level incident reports.",
    },
    {
        "key": "meric",
        "label": "MERIC labor and unemployment data",
        "domain": "labor market",
        "url": "https://meric.mo.gov/data/unemployment",
        "status": "indexed",
        "access": "Public reports, dashboard links, local unemployment data, and the LAUS CSV route.",
        "use_case": "Exact current Missouri/county unemployment rate, labor force, employment, and unemployed-count lookup; source discovery for wage, industry, projection, and regional profile questions.",
        "risk": "Many releases are PDFs or dashboards; exact current values need update timestamps.",
    },
    {
        "key": "dnr",
        "label": "Missouri DNR data and e-services",
        "domain": "environment",
        "url": "https://dnr.mo.gov/data-e-services",
        "status": "source indexed",
        "access": "Public environmental datasets, ArcGIS services, water permits, drinking water reports, impaired waters, and water-quality tools.",
        "use_case": "Water permits, public water systems, impaired waters, water quality, air/environmental reports, and GIS-style lookups.",
        "risk": "Many surfaces are search tools or map services; normalize by dataset before answering exact questions.",
    },
    {
        "key": "msdis",
        "label": "MSDIS geospatial open data",
        "domain": "geospatial",
        "url": "https://www.msdis.missouri.edu/",
        "status": "source indexed",
        "access": "Missouri GIS downloads, ArcGIS services, imagery, elevation, LiDAR, and vector layers.",
        "use_case": "County boundaries, administrative geography, public facilities, environmental overlays, and map-backed context.",
        "risk": "Imagery/LiDAR can be very large; start with vector metadata and small layers.",
    },
    {
        "key": "modot",
        "label": "MoDOT traffic and transportation data",
        "domain": "transportation",
        "url": "https://www.modot.org/modatazone/traffic",
        "status": "source indexed",
        "access": "Public MoDOT traffic data tools, reports, and transportation data pages.",
        "use_case": "Traffic counts, road/route context, safety/volume references, and transportation-data source discovery.",
        "risk": "Some values live behind apps or map tools; start with source links and downloadable reports.",
    },
    {
        "key": "state_auditor",
        "label": "Missouri State Auditor reports",
        "domain": "audits and accountability",
        "url": "https://auditor.mo.gov/AuditReport/Reports",
        "status": "indexed",
        "access": "Official audit-report search page plus structured report-search JSON endpoint.",
        "use_case": "Exact report metadata lookup for report numbers, titles, release dates, official report links, PDF links, recent reports, year counts, and keyword searches.",
        "risk": "Metadata lookup only; report PDFs are not downloaded and audit findings are not interpreted without a dedicated capped document parser.",
    },
    {
        "key": "dor_reports",
        "label": "Missouri Department of Revenue public reports",
        "domain": "tax and revenue",
        "url": "https://dor.mo.gov/public-reports/",
        "status": "indexed",
        "access": "Official downloadable public reports for taxable sales, food tax, tax credits, vehicle/dealer reports, and Working Family Tax Credit summaries.",
        "use_case": "Exact aggregate lookup for indexed county taxable sales, business locations, vehicle counts, driver totals, dealer counts, and SIC location counts; source discovery for other revenue reports.",
        "risk": "Some reports suppress small counts; preserve suppression symbols and explain update periods.",
    },
    {
        "key": "mec",
        "label": "Missouri Ethics Commission public records",
        "domain": "ethics and campaign finance",
        "url": "https://mec.mo.gov/",
        "status": "source indexed",
        "access": "Public campaign-finance, lobbying, committee, commission-action, annual-report, and ethics-law search surfaces.",
        "use_case": "Campaign finance, committee contributions/expenditures, lobbyist reports, commission actions, and public ethics-law context.",
        "risk": "Political-finance data needs careful entity matching and should distinguish filings from conclusions or allegations.",
    },
    {
        "key": "sos_elections",
        "label": "Missouri Secretary of State election results",
        "domain": "elections",
        "url": "https://www.sos.mo.gov/elections/s_default",
        "status": "indexed",
        "access": "Official election-results, candidate, ballot-measure, voter-turnout, and election-calendar pages.",
        "use_case": "Official election result source discovery plus selected exact statewide election-return lookup for winners, candidate votes, percentages, total votes, and primary party winners.",
        "risk": "Selected official-return PDFs only; not all result formats are bulk-download friendly, and voter files or precinct-level files are out of scope.",
    },
    {
        "key": "oa_budget",
        "label": "Office of Administration Budget and Planning",
        "domain": "budget and planning",
        "url": "https://oa.mo.gov/budget-and-planning",
        "status": "source indexed",
        "access": "Official budget, revenue, performance-measure, demographics, redistricting, and fiscal-policy pages.",
        "use_case": "Connect MAP spending to executive budget context, revenue estimates, performance measures, and state demographic planning.",
        "risk": "Budget documents can be proposal-stage or enacted-stage; label the stage and fiscal year.",
    },
    {
        "key": "child_care",
        "label": "DESE child care compliance dashboards",
        "domain": "child care",
        "url": "https://dese.mo.gov/childhood/child-care/child-care-data-dashboards",
        "status": "indexed",
        "access": "Public quarterly dashboard PDFs for regulated child care facilities, slots, inspections, complaint investigations, pending facilities, and licensing time.",
        "use_case": "Exact quarterly aggregate lookup for child-care slots, pending facilities, inspections, complaint investigations, facility type counts, and licensing-time percentages.",
        "risk": "Dashboard values are quarterly snapshots; cite the dashboard period and avoid facility-level or compliance conclusions beyond the aggregate source.",
    },
    {
        "key": "long_term_care",
        "label": "DHSS long-term care inspection data",
        "domain": "long-term care",
        "url": "https://health.mo.gov/safety/nursinghomesinspected/index.php",
        "status": "source indexed",
        "access": "Public long-term-care inspection pages and Show Me Long-Term Care search surfaces.",
        "use_case": "Nursing home, assisted living, residential care, facility-type, bed-count, inspection, and complaint source discovery; selected data.mo.gov LTC Directory and Census exact lookup is implemented.",
        "risk": "Health-care facility data should remain source-cited; avoid medical advice, unsupported quality rankings, or unstored contact/person fields.",
    },
    {
        "key": "psc",
        "label": "Missouri Public Service Commission reports",
        "domain": "utilities",
        "url": "https://psc.mo.gov/General/PSC_Reports",
        "status": "source indexed",
        "access": "Public PSC report volumes, utility information, annual report references, and rate-case context pages.",
        "use_case": "Explain utility regulation sources, rate-case documents, public reports, and utility consumer context.",
        "risk": "Utility cases are legal/regulatory records; distinguish filings, staff positions, orders, and final decisions.",
    },
    {
        "key": "cannabis",
        "label": "DHSS Division of Cannabis Regulation reports",
        "domain": "cannabis regulation",
        "url": "https://health.mo.gov/safety/cannabis/",
        "status": "indexed",
        "access": "Official cannabis-regulation pages, verified dispensary ArcGIS feature layer, annual-report PDFs, dashboards, and regulatory updates.",
        "use_case": "Exact verified dispensary counts/lookups and selected annual-report sales, tax, transfer, microbusiness, agent-card, and operating-facility metrics; broader dashboard/report source discovery remains cataloged.",
        "risk": "Current dashboards and facility locator data are time-sensitive; index sanitized non-contact facility fields and avoid legal advice.",
    },
    {
        "key": "agriculture",
        "label": "Missouri Agricultural Market News reports",
        "domain": "agriculture",
        "url": "https://agmarketnews.mo.gov/reports/",
        "status": "source indexed",
        "access": "Public agricultural market-report links for livestock, cattle, swine, sheep/goat, and regional auctions.",
        "use_case": "Agricultural price/report source discovery and plain-English market-report explanations.",
        "risk": "Market reports may link to federal AMS reports; cite report date and market region.",
    },
]


def catalog_by_status() -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in PUBLIC_SOURCE_CATALOG:
        grouped.setdefault(source["status"], []).append(source)
    return grouped
