"""Curated registry of Missouri public-data sources for the chatbot roadmap."""

from __future__ import annotations

from typing import Any


PUBLIC_SOURCE_CATALOG: list[dict[str, Any]] = [
    {
        "key": "map",
        "label": "Missouri Accountability Portal",
        "domain": "public finance",
        "url": "https://mapyourtaxes.mo.gov/Map/Portal/Default.aspx",
        "status": "indexed",
        "access": "Public downloads and daily-updated MAP web tables.",
        "use_case": "Expenditures, employee pay, tax credits, federal grants, budget restrictions, bonds, and related transparency questions.",
        "risk": "Row-level public records need careful UI limits and privacy boundaries.",
    },
    {
        "key": "data_mo_catalog",
        "label": "State of Missouri data.mo.gov catalog",
        "domain": "open data catalog",
        "url": "https://data.mo.gov/data.json",
        "status": "indexed",
        "access": "Socrata/data.json metadata and dataset CSV/JSON exports when public.",
        "use_case": "Exact catalog metadata lookup for dataset counts, themes, dataset search, landing pages, and distribution links; prioritizes future parsers.",
        "risk": "Dataset schemas vary; some views are maps, files, filters, or stale records.",
    },
    {
        "key": "data_mo_education",
        "label": "data.mo.gov education datasets",
        "domain": "education",
        "url": "https://data.mo.gov/browse?category=Education",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV exports for selected education datasets.",
        "use_case": "Exact school/year lookup for high-school senior counts and completed FAFSA application counts, plus top-school rankings.",
        "risk": "This is a selected open-data education layer, not full DESE accountability, assessment, staff, or finance coverage.",
    },
    {
        "key": "data_mo_health",
        "label": "data.mo.gov public-health aggregates",
        "domain": "public health",
        "url": "https://data.mo.gov/d/fk75-fa28",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Missouri Communicable Disease Report.",
        "use_case": "Exact aggregate communicable-disease report lookup for current-week YTD counts, rates per 100k, 5-year median comparisons, and rankings.",
        "risk": "Aggregate surveillance reporting only; not medical advice and not full DHSS MICA/profile coverage.",
    },
    {
        "key": "data_mo_wic",
        "label": "DHSS WIC aggregates",
        "domain": "public health",
        "url": "https://data.mo.gov/d/diyi-fr2a",
        "status": "indexed",
        "access": "Public Socrata aggregate queries over DHSS WIC Data.",
        "use_case": "Exact county and municipality WIC household-row counts, redeemed net-benefit totals, average benefits, and top-county rankings.",
        "risk": "The source table is household-level public data; this project stores and returns aggregate county/municipality summaries only.",
    },
    {
        "key": "data_mo_ltc",
        "label": "data.mo.gov LTC directory and census",
        "domain": "long-term care",
        "url": "https://data.mo.gov/d/fenu-sipv",
        "status": "indexed",
        "access": "Public Socrata JSON exports for selected sanitized LTC Directory fields and aggregate LTC Census Report rows.",
        "use_case": "Exact county/city/facility long-term-care directory capacity lookup, level-of-care summaries, top-county capacity ranking, and statewide LTC census occupancy.",
        "risk": "Selected directory and census fields only; administrator names, phone numbers, mailing addresses, street addresses, inspections, complaints, and quality conclusions are not stored or returned.",
    },
    {
        "key": "data_mo_water",
        "label": "data.mo.gov DNR water datasets",
        "domain": "environment",
        "url": "https://data.mo.gov/d/3mwf-kse4",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Consumer Confidence Report public drinking-water system listing.",
        "use_case": "Exact county water-system counts, PWSID lookups, system-name lookups, and county rankings.",
        "risk": "Selected drinking-water system listing only; not full DNR water quality, permits, impaired waters, or GIS coverage.",
    },
    {
        "key": "data_mo_utility",
        "label": "data.mo.gov utility providers",
        "domain": "utilities",
        "url": "https://data.mo.gov/d/yeiz-h2m2",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for the Find A Missouri Utility city/county table.",
        "use_case": "Exact city/county electric, gas, water, and telephone provider lookup plus provider rankings.",
        "risk": "Selected utility-provider listing only; not full PSC filings, rate cases, annual reports, or legal/regulatory orders.",
    },
    {
        "key": "data_mo_agriculture",
        "label": "data.mo.gov agriculture feed samples",
        "domain": "agriculture",
        "url": "https://data.mo.gov/d/y9w9-qkg2",
        "status": "indexed",
        "access": "Public Socrata JSON/CSV export for Missouri Department of Agriculture feed sample testing results.",
        "use_case": "Exact feed sample ID lookup, feed class counts and rankings, and selected nutrient guarantee/result questions.",
        "risk": "Selected feed sample testing table only; not full agricultural market reports, inspections, complaints, or enforcement coverage.",
    },
    {
        "key": "contracts",
        "label": "MissouriBUYS and OA contract search",
        "domain": "procurement",
        "url": "https://missouribuys.mo.gov/contractboard",
        "status": "indexed",
        "access": "Public contract board plus legacy OA statewide contract detail pages and document links.",
        "use_case": "Contract number, vendor, category, dates, document links, and MAP vendor-payment context.",
        "risk": "Legacy HTML/CGI structure can change; new MissouriBUYS transition may shift data surfaces.",
    },
    {
        "key": "contract_documents",
        "label": "OA contract award documents",
        "domain": "procurement documents",
        "url": "https://archive.oa.mo.gov/purch/contracts/",
        "status": "local optional extraction",
        "access": "Public PDF contract documents; downloaded and parsed locally only when a capped document index is built.",
        "use_case": "Plain-English contract explanations: what the state is buying, who the vendor is, term, renewal, contract type, and where to read the source document.",
        "risk": "PDF extraction can be imperfect; downloads must be capped to avoid storage spikes.",
    },
    {
        "key": "dese",
        "label": "DESE School Data",
        "domain": "education",
        "url": "https://dese.mo.gov/school-data",
        "status": "indexed",
        "access": "Official school-data pages, dashboards, school directory exports, and public MCDS/DESE app surfaces.",
        "use_case": "Exact metadata lookup for accountability/APR/MSIP, Core Data/MOSIS file layouts and code sets, school finance, assessment, and special-education resource links; selected School Directory, selected 2025 APR ranking, and selected 2025-2026 school-finance transfer exact lookups are also implemented.",
        "risk": "Resource metadata only for the broader school-data layer; selected APR ranking and transfer rows are parsed from published PDFs, but full MCDS numeric dashboard values, accountability calculations, staff rows, budgets, audits, and broader finance tables still need dedicated parsers. Contact/person fields from directory PDFs are suppressed.",
    },
    {
        "key": "dhss",
        "label": "DHSS Data, Surveillance Systems & Statistical Reports",
        "domain": "public health",
        "url": "https://health.mo.gov/data/",
        "status": "indexed",
        "access": "Public dashboards, profiles, reports, and aggregate health datasets.",
        "use_case": "Exact metadata lookup for county profiles, MOPHIMS/MICA tools, BRFSS, births/deaths, hospitalizations/PAS, county-level study, vital-statistics FOCUS reports, and surveillance dashboard links; selected communicable-disease, BRFSS statewide prevalence, statewide vital-statistics, MOPHIMS statewide profile, and WIC aggregate lookup is also implemented.",
        "risk": "Resource metadata only for the broader health layer; county-profile values, broader MOPHIMS/MICA query values, county-level BRFSS values, county-level births/deaths, vital-record certificates, patient-level records, and hospital discharge records still need aggregate parsers with suppression handling.",
    },
    {
        "key": "mshp_sac",
        "label": "MSHP Statistical Analysis Center data files",
        "domain": "public safety",
        "url": "https://www.mshp.dps.mo.gov/MSHPWeb/SAC/data_960grid.html",
        "status": "indexed",
        "access": "Small public Excel files for crime, crash, traffic arrest, and related aggregate tables.",
        "use_case": "Crash severity, fatalities, injuries, rates, alcohol/speed/young-driver/older-driver/commercial/motorcycle factors.",
        "risk": "Excel parsing dependency; avoid person-level incident reports.",
    },
    {
        "key": "meric",
        "label": "MERIC labor and unemployment data",
        "domain": "labor market",
        "url": "https://meric.mo.gov/data/unemployment",
        "status": "indexed",
        "access": "Public reports, dashboard links, local unemployment data, and the LAUS CSV route.",
        "use_case": "Exact current Missouri/county unemployment rate, labor force, employment, and unemployed-count lookup; source discovery for wage, industry, projection, and regional profile questions.",
        "risk": "Many releases are PDFs or dashboards; exact current values need update timestamps.",
    },
    {
        "key": "dnr",
        "label": "Missouri DNR data and e-services",
        "domain": "environment",
        "url": "https://dnr.mo.gov/data-e-services",
        "status": "indexed",
        "access": "Public environmental datasets, ArcGIS services, water permits, drinking water tools, impaired waters, water-quality tools, air-emissions tools, waste/recycling resources, land/geology maps, energy data, forms, and public notices.",
        "use_case": "Exact metadata lookup for DNR data/e-services resource links; selected data.mo.gov DNR water exact lookup is also implemented for public drinking-water system rows.",
        "risk": "Resource metadata only for the broader DNR layer; numeric water-quality, permit, impaired-water, emission, waste-site, and geospatial values still need dedicated parsers.",
    },
    {
        "key": "msdis",
        "label": "MSDIS geospatial open data",
        "domain": "geospatial",
        "url": "https://www.msdis.missouri.edu/",
        "status": "indexed",
        "access": "Missouri GIS downloads, ArcGIS services, imagery, elevation, LiDAR, and vector layers.",
        "use_case": "Exact metadata lookup for MSDIS Open Data, ArcGIS REST feature/map/image services, county boundaries, imagery, LiDAR/elevation, archive directories, and vector GIS resource links.",
        "risk": "Metadata lookup only; imagery, LiDAR, feature layers, shapefiles, geodatabases, coordinates, and GIS attribute values are not downloaded by default.",
    },
    {
        "key": "modot",
        "label": "MoDOT traffic and transportation data",
        "domain": "transportation",
        "url": "https://www.modot.org/modatazone/traffic",
        "status": "indexed",
        "access": "Public MoDOT traffic data tools, traffic-volume map page, and official TrafficInfoSegAADT ArcGIS REST service.",
        "use_case": "Exact latest-year directional AADT lookup for indexed route segments, highest-volume route questions, direction filters, and traffic-volume source discovery.",
        "risk": "AADT lookup is route/segment-text based and does not geocode addresses; broader MoDOT map/app values still need source-specific parsers.",
    },
    {
        "key": "state_auditor",
        "label": "Missouri State Auditor reports",
        "domain": "audits and accountability",
        "url": "https://auditor.mo.gov/AuditReport/Reports",
        "status": "indexed",
        "access": "Official audit-report search page, structured report-search JSON endpoint, and capped selected official PDF downloads.",
        "use_case": "Exact report metadata lookup for report numbers, titles, release dates, official report links, PDF links, recent reports, year counts, keyword searches, and selected plain-English PDF orientation.",
        "risk": "The PDF text layer is capped and selected; it is not a complete audit archive, legal analysis, or substitute for the official report wording.",
    },
    {
        "key": "dor_reports",
        "label": "Missouri Department of Revenue public reports",
        "domain": "tax and revenue",
        "url": "https://dor.mo.gov/public-reports/",
        "status": "indexed",
        "access": "Official downloadable public reports for taxable sales, food tax, tax credits, vehicle/dealer reports, and Working Family Tax Credit summaries.",
        "use_case": "Exact aggregate lookup for indexed county taxable sales, business locations, vehicle counts, driver totals, dealer counts, and SIC location counts; source discovery for other revenue reports.",
        "risk": "Some reports suppress small counts; preserve suppression symbols and explain update periods.",
    },
    {
        "key": "mec",
        "label": "Missouri Ethics Commission public records",
        "domain": "ethics and campaign finance",
        "url": "https://mec.mo.gov/",
        "status": "indexed",
        "access": "Public campaign-finance, lobbying, committee, commission-action, annual-report, and ethics-law search surfaces.",
        "use_case": "Exact public-resource metadata lookup for campaign-finance searches, Committee Contributions & Expenditures, lobbying searches/reports, commission actions, advisory opinions, forms, financial disclosure/PFD resources, and annual reports.",
        "risk": "Political-finance data needs careful entity matching and should distinguish filings from conclusions or allegations.",
    },
    {
        "key": "sos_elections",
        "label": "Missouri Secretary of State election results",
        "domain": "elections",
        "url": "https://www.sos.mo.gov/elections/s_default",
        "status": "indexed",
        "access": "Official election-results, candidate, ballot-measure, voter-turnout, and election-calendar pages.",
        "use_case": "Official election result source discovery plus selected exact statewide election-return lookup for winners, candidate votes, percentages, total votes, and primary party winners.",
        "risk": "Selected official-return PDFs only; not all result formats are bulk-download friendly, and voter files or precinct-level files are out of scope.",
    },
    {
        "key": "oa_budget",
        "label": "Office of Administration Budget and Planning",
        "domain": "budget and planning",
        "url": "https://budplan.oa.mo.gov/budget-information",
        "status": "indexed",
        "access": "Official budget, revenue, performance-measure, demographics, redistricting, and fiscal-policy pages.",
        "use_case": "Exact Budget and Planning metadata lookup for executive budget links, budget summaries, revenue releases/detail files, performance-measure resources, demographic resources, and redistricting resources.",
        "risk": "Metadata only; budget documents can be proposal-stage or enacted-stage, and PDF/Excel contents are not interpreted.",
    },
    {
        "key": "child_care",
        "label": "DESE child care compliance dashboards",
        "domain": "child care",
        "url": "https://dese.mo.gov/childhood/child-care/child-care-data-dashboards",
        "status": "indexed",
        "access": "Public quarterly dashboard PDFs for regulated child care facilities, slots, inspections, complaint investigations, pending facilities, and licensing time.",
        "use_case": "Exact quarterly aggregate lookup for child-care slots, pending facilities, inspections, complaint investigations, facility type counts, and licensing-time percentages.",
        "risk": "Dashboard values are quarterly snapshots; cite the dashboard period and avoid facility-level or compliance conclusions beyond the aggregate source.",
    },
    {
        "key": "long_term_care",
        "label": "DHSS long-term care inspection data",
        "domain": "long-term care",
        "url": "https://health.mo.gov/safety/nursinghomesinspected/index.php",
        "status": "indexed",
        "access": "Public long-term-care inspection pages and Show Me Long-Term Care search surfaces.",
        "use_case": "Nursing home, assisted living, residential care, facility-type, inspection-source, county/city search-filter, scope/severity, and complaint-source discovery; selected data.mo.gov LTC Directory/Census and DHSS LTC inspection resource/filter exact lookup are implemented.",
        "risk": "Health-care facility data should remain source-cited; avoid medical advice, unsupported quality rankings, unparsed facility findings, or unstored contact/person fields.",
    },
    {
        "key": "psc",
        "label": "Missouri Public Service Commission reports",
        "domain": "utilities",
        "url": "https://psc.mo.gov/General/PSC_Reports",
        "status": "indexed",
        "access": "Public PSC report volumes, utility information, annual report references, and rate-case context pages.",
        "use_case": "Exact PSC report metadata lookup for official report volumes, covered periods, year-to-volume matching, and PDF links; broader utility case interpretation remains source discovery.",
        "risk": "Utility cases are legal/regulatory records; this index links report metadata only and does not interpret filings, staff positions, orders, or final decisions.",
    },
    {
        "key": "cannabis",
        "label": "DHSS Division of Cannabis Regulation reports",
        "domain": "cannabis regulation",
        "url": "https://health.mo.gov/safety/cannabis/",
        "status": "indexed",
        "access": "Official cannabis-regulation pages, verified dispensary ArcGIS feature layer, annual-report PDFs, dashboards, and regulatory updates.",
        "use_case": "Exact verified dispensary counts/lookups and selected annual-report sales, tax, transfer, microbusiness, agent-card, and operating-facility metrics; broader dashboard/report source discovery remains cataloged.",
        "risk": "Current dashboards and facility locator data are time-sensitive; index sanitized non-contact facility fields and avoid legal advice.",
    },
    {
        "key": "agriculture",
        "label": "Missouri Agricultural Market News reports",
        "domain": "agriculture",
        "url": "https://agmarketnews.mo.gov/reports/",
        "status": "indexed",
        "access": "Public agricultural market-report links for livestock, cattle, swine, sheep/goat, and regional auctions.",
        "use_case": "Exact Agricultural Market News report metadata lookup for cattle/livestock, swine, sheep/goat, hay/forage, feedstuff, grain, regional market, and USDA AMS report links.",
        "risk": "Metadata only; linked PDF/dashboard contents, prices, receipts, weights, and market commentary are not interpreted.",
    },
]


def catalog_by_status() -> dict[str, list[dict[str, Any]]]:
    grouped: dict[str, list[dict[str, Any]]] = {}
    for source in PUBLIC_SOURCE_CATALOG:
        grouped.setdefault(source["status"], []).append(source)
    return grouped
